# -*- coding: utf-8 -*-
"""memoriaVariaveis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f8VhXgukB78Em23Qm34g9W0pUtTuC1Fk
"""

x = 15
y = x 
print("id de x: ", id(x))
print("id de y: ", id(y))
x = 20
print("id de x: ", id(x))
print("id de y: ", id(y))
print(x)
print(y)