# -*- coding: utf-8 -*-
"""escopoVariaveis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f8VhXgukB78Em23Qm34g9W0pUtTuC1Fk
"""

def somar(x, y):
  soma = x + y
  s = soma
  print(s)
  print(soma)
  return soma

a = 5
b = 6
s = somar(a, b)
print(s)
print(soma)