# -*- coding: utf-8 -*-
"""valorxReferencia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f8VhXgukB78Em23Qm34g9W0pUtTuC1Fk
"""

def incrementar(x):
  x = x + 1
  print(x)
  print("id de x em incrementar: ", id(x))

x = 10
print("valor inicial de x:", x)
print("id de x:", id(x))
incrementar(x)
print("valor final de x após incrementar:", x) # valor não mudou
print("id de x:", id(x))

def ordenar(k):
  x = k
  x.sort()
  print("id de x:", id(x))
  print("id de k:", id(k))

y = [5, 3, 7, 2, 4]
print("id de y:", id(y))
ordenar(y)
print(y)

import copy

def ordenar(k):
  x = copy.copy(k) 
  print(id(x[0]))
  print(id(k[0]))
  x.sort()
  print("id de x:", id(x))
  print("id de k:", id(k))


y = [5, 3, 7, 2, 4]
print("id de y:", id(y))
ordenar(y)
print(y)